language: android
sudo: true
android:
  components:
    - tools
    - platform-tools
    - extra-google-m2repository
    - extra-android-m2repository
addons:
  apt_packages:
    - pandoc
before_install:
  - sudo apt-get install ant
script:
  - ./_travis.sh
