name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 11.0
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Build example
      run: |
        sudo apt-get install ninja-build
        cd example
        ../premake5 android-studio
        cd build
        gradle wrapper
        ./gradlew build
