name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build example
      run: |
        sudo apt-get install ninja-build
        cd example
        ls
        rm -rf build
        ../premake5 android-studio
        cd build
        gradle build
