name: ci
on:
  push:
  pull_request:
    branches: [ "main", "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11.0

    #- name: Setup Android SDK
    #  uses: android-actions/setup-android@v2

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
          gradle-version: 7.5.1

    - name: Build example
      run: |
        sudo apt-get install ninja-build
        cd example
        ../premake5 android-studio
        cd build
        gradle wrapper
        ./gradlew build
